In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mysql.connector
from sqlalchemy import create_engine

In [4]:
df=pd.read_csv(r"C:\Users\KOTHAPALLI JOHNSON\Downloads/ecommerce_sales_data.CSV")
df.head()

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-12-31      Printer       Office  North         4   3640  348.93
1  2022-11-27        Mouse  Accessories   East         7   1197  106.53
2  2022-05-11       Tablet  Electronics  South         5   5865  502.73
3  2024-03-16        Mouse  Accessories  South         2    786  202.87
4  2022-09-10        Mouse  Accessories   West         1    509  103.28

In [5]:
df.shape

(3500, 7)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order Date    3500 non-null   str
 1   Product Name  3500 non-null   str
 2   Category      3500 non-null   str
 3   Region        3500 non-null   str
 4   Quantity      3500 non-null   int64
 5   Sales         3500 non-null   int64
 6   Profit        3500 non-null   float64
dtypes: float64(1), int64(2), str(4)
memory usage: 191.5 KB

In [7]:
df.columns

Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='str')

In [8]:
df.describe

<bound method NDFrame.describe of       Order Date Product Name     Category Region  Quantity  Sales   Profit
0     2024-12-31      Printer       Office  North         4   3640   348.93
1     2022-11-27        Mouse  Accessories   East         7   1197   106.53
2     2022-05-11       Tablet  Electronics  South         5   5865   502.73
3     2024-03-16        Mouse  Accessories  South         2    786   202.87
4     2022-09-10        Mouse  Accessories   West         1    509   103.28
...          ...          ...          ...    ...       ...    ...      ...
3495  2023-02-15      Monitor  Accessories  North         4   4064   771.16
3496  2022-09-18      Monitor  Accessories   East         1   1117   119.89
3497  2022-04-12       Laptop  Electronics  South         4    260    66.02
3498  2022-01-18      Printer       Office  South         3    222    50.28
3499  2024-11-01   Smartwatch  Electronics   East         9  10530  1777.32

[3500 rows x 7 columns]>

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          0
dtype: int64

In [11]:
df.dtypes

Order Date          str
Product Name        str
Category            str
Region              str
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [12]:
iqr = df['Quantity'].quantile(0.75) - df['Quantity'].quantile(0.25)
upper_threshold = df['Quantity'].quantile(0.75) + (1.5*iqr)  #Q3+1.5*IQR
lower_thrshold = df['Quantity'].quantile(0.25) - (1.5*iqr)   #Q1-1.5*IQR
print(upper_threshold,",",lower_thrshold)

13.0 , -3.0

In [13]:
df['Quantity']=df['Quantity'].clip(lower_thrshold,upper_threshold)

In [14]:
iqr = df['Sales'].quantile(0.75) - df['Sales'].quantile(0.25)
upper_threshold = df['Sales'].quantile(0.75) + (1.5*iqr)  #Q3+1.5*IQR
lower_thrshold = df['Sales'].quantile(0.25) - (1.5*iqr)   #Q1-1.5*IQR
print(upper_threshold,",",lower_thrshold)

9768.25 , -4181.75

In [15]:
df['Sales']=df['Sales'].clip(lower_thrshold,upper_threshold)

In [16]:
iqr = df['Profit'].quantile(0.75) - df['Profit'].quantile(0.25)
upper_threshold = df['Profit'].quantile(0.75) + (1.5*iqr)  #Q3+1.5*IQR
lower_thrshold = df['Profit'].quantile(0.25) - (1.5*iqr)   #Q1-1.5*IQR
print(upper_threshold,",",lower_thrshold)

1584.77 , -696.95

In [17]:
df['Profit']=df['Profit'].clip(lower_thrshold,upper_threshold)

In [18]:
df.describe()

          Quantity        Sales       Profit
count  3500.000000  3500.000000  3500.000000
mean      4.931714  3043.241357   506.819880
std       2.575895  2426.488190   444.805296
min       1.000000    51.000000     6.970000
25%       3.000000  1049.500000   158.695000
50%       5.000000  2350.500000   361.070000
75%       7.000000  4537.000000   729.125000
max       9.000000  9768.250000  1584.770000

In [19]:
df["Category"].unique()

<StringArray>
['Office', 'Accessories', 'Electronics']
Length: 3, dtype: str

In [20]:
df["Region"].unique()

<StringArray>
['North', 'East', 'South', 'West']
Length: 4, dtype: str

In [21]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [22]:
df["Quantity"] = pd.to_numeric(df["Quantity"])
df["Sales"] = pd.to_numeric(df["Sales"])
df["Profit"] = pd.to_numeric(df["Profit"])

In [23]:
df.dtypes

Order Date      datetime64[us]
Product Name               str
Category                   str
Region                     str
Quantity                 int64
Sales                  float64
Profit                 float64
dtype: object

In [24]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [25]:
df[df["Sales"] < 0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [26]:
df[df["Sales"] == 0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [27]:
df[df["Profit"] < 0]

Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [28]:
df["Year"] = df["Order Date"].dt.year

In [29]:
df["Month"] = df["Order Date"].dt.month

In [30]:
df["Month_Name"] = df["Order Date"].dt.month_name()

In [31]:
df["Quarter"] = df["Order Date"].dt.quarter

In [32]:
df["Profit_Margin"] = (df["Profit"] / df["Sales"]) * 100

In [33]:
df.head()

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Year,Month,Month_Name,Quarter,Profit_Margin
0,2024-12-31,Printer,Office,North,4,3640.0,348.93,2024,12,December,4,9.585989
1,2022-11-27,Mouse,Accessories,East,7,1197.0,106.53,2022,11,November,4,8.899749
2,2022-05-11,Tablet,Electronics,South,5,5865.0,502.73,2022,5,May,2,8.571697
3,2024-03-16,Mouse,Accessories,South,2,786.0,202.87,2024,3,March,1,25.810433
4,2022-09-10,Mouse,Accessories,West,1,509.0,103.28,2022,9,September,3,20.290766

In [34]:
overall_profit_margin = (df["Profit"].sum() / df["Sales"].sum()) * 100

In [35]:
total_sales = df["Sales"].sum()
total_sales

np.float64(10651344.75)

In [36]:
total_profit = df["Profit"].sum()
total_profit

np.float64(1773869.58)

In [37]:
total_quantity = df["Quantity"].sum()
total_quantity

np.int64(17261)

In [38]:
total_transactions = df.shape[0]
total_transactions

3500

In [39]:
overall_profit_margin = (total_profit / total_sales) * 100
overall_profit_margin

np.float64(16.65394954003343)

In [40]:
average_transaction_value = total_sales / total_transactions
average_transaction_value

np.float64(3043.241357142857)

In [41]:
print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Quantity:", total_quantity)
print("Total Transactions:", total_transactions)
print("Profit Margin:", round(overall_profit_margin, 2), "%")
print("Average Transaction Value:", round(average_transaction_value, 2))

Total Sales: 10651344.75
Total Profit: 1773869.58
Total Quantity: 17261
Total Transactions: 3500
Profit Margin: 16.65 %
Average Transaction Value: 3043.24

In [42]:
monthly_sales = df.groupby(["Year", "Month"])["Sales"].sum().reset_index()

monthly_sales

    Year  Month      Sales
0   2022      1  341544.00
1   2022      2  208775.00
2   2022      3  294618.25
3   2022      4  230624.00
4   2022      5  313407.25
5   2022      6  272891.25
6   2022      7  214378.25
7   2022      8  296242.00
8   2022      9  239686.50
9   2022     10  324680.50
10  2022     11  256250.25
11  2022     12  259041.00
12  2023      1  342818.25
13  2023      2  313079.25
14  2023      3  303391.00
15  2023      4  279035.75
16  2023      5  346115.25
17  2023      6  251686.00
18  2023      7  320798.00
19  2023      8  387426.50
20  2023      9  302335.50
21  2023     10  253145.00
22  2023     11  306195.00
23  2023     12  372335.25
24  2024      1  281959.75
25  2024      2  179708.00
26  2024      3  340873.25
27  2024      4  309544.75
28  2024      5  373536.25
29  2024      6  314268.00
30  2024      7  309515.00
31  2024      8  239507.25
32  2024      9  341926.00
33  2024     10  314003.25
34  2024     11  291007.25
35  2024     12  324997.00

In [43]:
monthly_profit = df.groupby(["Year", "Month"])["Profit"].sum().reset_index()

monthly_profit

    Year  Month    Profit
0   2022      1  60944.43
1   2022      2  33678.95
2   2022      3  50914.10
3   2022      4  42198.15
4   2022      5  51674.43
5   2022      6  46276.68
6   2022      7  37954.47
7   2022      8  45525.03
8   2022      9  39071.99
9   2022     10  52303.77
10  2022     11  46581.41
11  2022     12  43738.08
12  2023      1  60220.26
13  2023      2  50446.07
14  2023      3  51764.89
15  2023      4  47949.65
16  2023      5  56336.71
17  2023      6  42358.10
18  2023      7  54397.12
19  2023      8  62611.64
20  2023      9  49126.22
21  2023     10  43052.73
22  2023     11  50518.03
23  2023     12  69628.86
24  2024      1  48041.38
25  2024      2  29679.32
26  2024      3  54771.87
27  2024      4  50114.47
28  2024      5  59838.10
29  2024      6  48861.34
30  2024      7  51870.58
31  2024      8  37895.65
32  2024      9  57417.18
33  2024     10  51945.25
34  2024     11  41966.86
35  2024     12  52195.81

In [44]:
monthly_performance = df.groupby(
    ["Year", "Month"]
).agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
).reset_index()

monthly_performance

    Year  Month  Total_Sales  Total_Profit
0   2022      1    341544.00      60944.43
1   2022      2    208775.00      33678.95
2   2022      3    294618.25      50914.10
3   2022      4    230624.00      42198.15
4   2022      5    313407.25      51674.43
5   2022      6    272891.25      46276.68
6   2022      7    214378.25      37954.47
7   2022      8    296242.00      45525.03
8   2022      9    239686.50      39071.99
9   2022     10    324680.50      52303.77
10  2022     11    256250.25      46581.41
11  2022     12    259041.00      43738.08
12  2023      1    342818.25      60220.26
13  2023      2    313079.25      50446.07
14  2023      3    303391.00      51764.89
15  2023      4    279035.75      47949.65
16  2023      5    346115.25      56336.71
17  2023      6    251686.00      42358.10
18  2023      7    320798.00      54397.12
19  2023      8    387426.50      62611.64
20  2023      9    302335.50      49126.22
21  2023     10    253145.00      43052.73
22  2023     11    306195.00      50518.03
23  2023     12    372335.25      69628.86
24  2024      1    281959.75      48041.38
25  2024      2    179708.00      29679.32
26  2024      3    340873.25      54771.87
27  2024      4    309544.75      50114.47
28  2024      5    373536.25      59838.10
29  2024      6    314268.00      48861.34
30  2024      7    309515.00      51870.58
31  2024      8    239507.25      37895.65
32  2024      9    341926.00      57417.18
33  2024     10    314003.25      51945.25
34  2024     11    291007.25      41966.86
35  2024     12    324997.00      52195.81

In [45]:
monthly_performance = monthly_performance.sort_values(
    ["Year", "Month"]
)

monthly_performance

    Year  Month  Total_Sales  Total_Profit
0   2022      1    341544.00      60944.43
1   2022      2    208775.00      33678.95
2   2022      3    294618.25      50914.10
3   2022      4    230624.00      42198.15
4   2022      5    313407.25      51674.43
5   2022      6    272891.25      46276.68
6   2022      7    214378.25      37954.47
7   2022      8    296242.00      45525.03
8   2022      9    239686.50      39071.99
9   2022     10    324680.50      52303.77
10  2022     11    256250.25      46581.41
11  2022     12    259041.00      43738.08
12  2023      1    342818.25      60220.26
13  2023      2    313079.25      50446.07
14  2023      3    303391.00      51764.89
15  2023      4    279035.75      47949.65
16  2023      5    346115.25      56336.71
17  2023      6    251686.00      42358.10
18  2023      7    320798.00      54397.12
19  2023      8    387426.50      62611.64
20  2023      9    302335.50      49126.22
21  2023     10    253145.00      43052.73
22  2023     11    306195.00      50518.03
23  2023     12    372335.25      69628.86
24  2024      1    281959.75      48041.38
25  2024      2    179708.00      29679.32
26  2024      3    340873.25      54771.87
27  2024      4    309544.75      50114.47
28  2024      5    373536.25      59838.10
29  2024      6    314268.00      48861.34
30  2024      7    309515.00      51870.58
31  2024      8    239507.25      37895.65
32  2024      9    341926.00      57417.18
33  2024     10    314003.25      51945.25
34  2024     11    291007.25      41966.86
35  2024     12    324997.00      52195.81

In [46]:
monthly_performance["Year_Month"] = (
    monthly_performance["Year"].astype(str)
    + "-"
    + monthly_performance["Month"].astype(str).str.zfill(2)
)

In [47]:
monthly_performance

    Year  Month  Total_Sales  Total_Profit Year_Month
0   2022      1    341544.00      60944.43    2022-01
1   2022      2    208775.00      33678.95    2022-02
2   2022      3    294618.25      50914.10    2022-03
3   2022      4    230624.00      42198.15    2022-04
4   2022      5    313407.25      51674.43    2022-05
5   2022      6    272891.25      46276.68    2022-06
6   2022      7    214378.25      37954.47    2022-07
7   2022      8    296242.00      45525.03    2022-08
8   2022      9    239686.50      39071.99    2022-09
9   2022     10    324680.50      52303.77    2022-10
10  2022     11    256250.25      46581.41    2022-11
11  2022     12    259041.00      43738.08    2022-12
12  2023      1    342818.25      60220.26    2023-01
13  2023      2    313079.25      50446.07    2023-02
14  2023      3    303391.00      51764.89    2023-03
15  2023      4    279035.75      47949.65    2023-04
16  2023      5    346115.25      56336.71    2023-05
17  2023      6    251686.00      42358.10    2023-06
18  2023      7    320798.00      54397.12    2023-07
19  2023      8    387426.50      62611.64    2023-08
20  2023      9    302335.50      49126.22    2023-09
21  2023     10    253145.00      43052.73    2023-10
22  2023     11    306195.00      50518.03    2023-11
23  2023     12    372335.25      69628.86    2023-12
24  2024      1    281959.75      48041.38    2024-01
25  2024      2    179708.00      29679.32    2024-02
26  2024      3    340873.25      54771.87    2024-03
27  2024      4    309544.75      50114.47    2024-04
28  2024      5    373536.25      59838.10    2024-05
29  2024      6    314268.00      48861.34    2024-06
30  2024      7    309515.00      51870.58    2024-07
31  2024      8    239507.25      37895.65    2024-08
32  2024      9    341926.00      57417.18    2024-09
33  2024     10    314003.25      51945.25    2024-10
34  2024     11    291007.25      41966.86    2024-11
35  2024     12    324997.00      52195.81    2024-12

In [48]:
monthly_performance.loc[
    monthly_performance["Total_Sales"].idxmax()
]

Year                2023
Month                  8
Total_Sales     387426.5
Total_Profit    62611.64
Year_Month       2023-08
Name: 19, dtype: object

In [49]:
monthly_performance.loc[
    monthly_performance["Total_Profit"].idxmax()
]

Year                 2023
Month                  12
Total_Sales     372335.25
Total_Profit     69628.86
Year_Month        2023-12
Name: 23, dtype: object

In [50]:
category_sales = df.groupby("Category")["Sales"].sum().reset_index()

category_sales = category_sales.sort_values(
    "Sales", ascending=False
)

category_sales

      Category       Sales
1  Electronics  5317427.00
0  Accessories  4240589.50
2       Office  1093328.25

In [51]:
category_profit = df.groupby("Category")["Profit"].sum().reset_index()

category_profit = category_profit.sort_values(
    "Profit", ascending=False
)

category_profit

      Category     Profit
1  Electronics  884006.17
0  Accessories  710487.60
2       Office  179375.81

In [52]:
category_quantity = df.groupby("Category")["Quantity"].sum().reset_index()

category_quantity = category_quantity.sort_values(
    "Quantity", ascending=False
)

category_quantity

      Category  Quantity
1  Electronics      8610
0  Accessories      6917
2       Office      1734

In [53]:
category_performance = df.groupby("Category").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Transactions=("Category", "count")
).reset_index()

category_performance

      Category  Total_Sales  Total_Profit  Total_Quantity  Transactions
0  Accessories   4240589.50     710487.60            6917          1401
1  Electronics   5317427.00     884006.17            8610          1742
2       Office   1093328.25     179375.81            1734           357

In [54]:
category_performance["Profit_Margin"] = (
    category_performance["Total_Profit"]
    / category_performance["Total_Sales"]
) * 100

In [55]:
category_performance = category_performance.sort_values(
    "Total_Sales",
    ascending=False
)

category_performance

,Category,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
1,Electronics,5317427.00,884006.17,8610,1742,16.624698
0,Accessories,4240589.50,710487.60,6917,1401,16.754454
2,Office,1093328.25,179375.81,1734,357,16.406400

In [56]:
product_sales = df.groupby("Product Name")["Sales"].sum().reset_index()

product_sales = product_sales.sort_values(
    "Sales",
    ascending=False
)

product_sales.head(10)

  Product Name       Sales
0       Camera  1175924.50
4      Monitor  1157055.00
6      Printer  1093328.25
5        Mouse  1073423.50
7   Smartphone  1067687.00
8   Smartwatch  1047528.75
9       Tablet  1023244.75
2     Keyboard  1022192.25
3       Laptop  1003042.00
1   Headphones   987918.75

In [57]:
product_profit = df.groupby("Product Name")["Profit"].sum().reset_index()

product_profit = product_profit.sort_values(
    "Profit",
    ascending=False
)

product_profit.head(10)

  Product Name     Profit
0       Camera  198904.18
4      Monitor  192881.61
6      Printer  179375.81
5        Mouse  179067.03
7   Smartphone  174488.17
8   Smartwatch  174407.90
3       Laptop  173971.14
1   Headphones  169404.98
2     Keyboard  169133.98
9       Tablet  162234.78

In [58]:
product_quantity = df.groupby("Product Name")["Quantity"].sum().reset_index()

product_quantity = product_quantity.sort_values(
    "Quantity",
    ascending=False
)

product_quantity.head(10)

  Product Name  Quantity
4      Monitor      1876
8   Smartwatch      1807
0       Camera      1795
5        Mouse      1753
6      Printer      1734
9       Tablet      1733
2     Keyboard      1684
3       Laptop      1658
7   Smartphone      1617
1   Headphones      1604

In [59]:
product_performance = df.groupby("Product Name").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Transactions=("Product Name", "count")
).reset_index()

In [60]:
product_performance["Profit_Margin"] = (
    product_performance["Total_Profit"]
    / product_performance["Total_Sales"]
) * 100

In [61]:
product_performance = product_performance.sort_values(
    "Total_Sales",
    ascending=False
)

product_performance.head(10)

,Product Name,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
0,Camera,1175924.50,198904.18,1795,363,16.914707
4,Monitor,1157055.00,192881.61,1876,364,16.670047
6,Printer,1093328.25,179375.81,1734,357,16.406400
5,Mouse,1073423.50,179067.03,1753,347,16.681862
7,Smartphone,1067687.00,174488.17,1617,330,16.342633
8,Smartwatch,1047528.75,174407.90,1807,363,16.649462
9,Tablet,1023244.75,162234.78,1733,350,15.854934
2,Keyboard,1022192.25,169133.98,1684,351,16.546201
3,Laptop,1003042.00,173971.14,1658,336,17.344352
1,Headphones,987918.75,169404.98,1604,339,17.147663

In [62]:
top_profit_products = product_performance.sort_values(
    "Total_Profit",
    ascending=False
)

top_profit_products.head(10)

,Product Name,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
0,Camera,1175924.50,198904.18,1795,363,16.914707
4,Monitor,1157055.00,192881.61,1876,364,16.670047
6,Printer,1093328.25,179375.81,1734,357,16.406400
5,Mouse,1073423.50,179067.03,1753,347,16.681862
7,Smartphone,1067687.00,174488.17,1617,330,16.342633
8,Smartwatch,1047528.75,174407.90,1807,363,16.649462
3,Laptop,1003042.00,173971.14,1658,336,17.344352
1,Headphones,987918.75,169404.98,1604,339,17.147663
2,Keyboard,1022192.25,169133.98,1684,351,16.546201
9,Tablet,1023244.75,162234.78,1733,350,15.854934

In [63]:
region_sales = df.groupby("Region")["Sales"].sum().reset_index()

region_sales = region_sales.sort_values(
    "Sales",
    ascending=False
)

region_sales

  Region       Sales
3   West  2838510.50
0   East  2672663.50
2  South  2655713.00
1  North  2484457.75

In [64]:
region_profit = df.groupby("Region")["Profit"].sum().reset_index()

region_profit = region_profit.sort_values(
    "Profit",
    ascending=False
)

region_profit

  Region     Profit
3   West  474209.18
0   East  447537.66
2  South  441152.75
1  North  410969.99

In [65]:
region_quantity = df.groupby("Region")["Quantity"].sum().reset_index()

region_quantity = region_quantity.sort_values(
    "Quantity",
    ascending=False
)

region_quantity

  Region  Quantity
3   West      4488
2  South      4361
0   East      4306
1  North      4106

In [66]:
region_performance = df.groupby("Region").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Transactions=("Region", "count")
).reset_index()

In [67]:
region_performance["Profit_Margin"] = (
    region_performance["Total_Profit"]
    / region_performance["Total_Sales"]
) * 100

In [68]:
region_performance = region_performance.sort_values(
    "Total_Sales",
    ascending=False
)

region_performance

,Region,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
3,West,2838510.50,474209.18,4488,898,16.706268
0,East,2672663.50,447537.66,4306,861,16.745006
2,South,2655713.00,441152.75,4361,883,16.611462
1,North,2484457.75,410969.99,4106,858,16.541637

In [69]:
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()

overall_margin = (total_profit / total_sales) * 100

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Overall Profit Margin:", round(overall_margin, 2), "%")

Total Sales: 10651344.75
Total Profit: 1773869.58
Overall Profit Margin: 16.65 %

In [70]:
category_performance[
    ["Category", "Total_Sales", "Total_Profit", "Profit_Margin"]
]

      Category  Total_Sales  Total_Profit  Profit_Margin
1  Electronics   5317427.00     884006.17      16.624698
0  Accessories   4240589.50     710487.60      16.754454
2       Office   1093328.25     179375.81      16.406400

In [71]:
category_performance.sort_values(
    "Profit_Margin",
    ascending=False
)

,Category,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
0,Accessories,4240589.50,710487.60,6917,1401,16.754454
1,Electronics,5317427.00,884006.17,8610,1742,16.624698
2,Office,1093328.25,179375.81,1734,357,16.406400

In [72]:
region_performance[
    ["Region", "Total_Sales", "Total_Profit", "Profit_Margin"]
]

  Region  Total_Sales  Total_Profit  Profit_Margin
3   West   2838510.50     474209.18      16.706268
0   East   2672663.50     447537.66      16.745006
2  South   2655713.00     441152.75      16.611462
1  North   2484457.75     410969.99      16.541637

In [73]:
region_performance.sort_values(
    "Profit_Margin",
    ascending=False
)

,Region,Total_Sales,Total_Profit,Total_Quantity,Transactions,Profit_Margin
0,East,2672663.50,447537.66,4306,861,16.745006
3,West,2838510.50,474209.18,4488,898,16.706268
2,South,2655713.00,441152.75,4361,883,16.611462
1,North,2484457.75,410969.99,4106,858,16.541637

In [74]:
sales_threshold = product_performance["Total_Sales"].median()
profit_threshold = product_performance["Total_Profit"].median()

print("Sales Threshold:", sales_threshold)
print("Profit Threshold:", profit_threshold)

Sales Threshold: 1057607.875
Profit Threshold: 174448.035

In [75]:
high_sales_low_profit = product_performance[
    (product_performance["Total_Sales"] > sales_threshold) &
    (product_performance["Total_Profit"] < profit_threshold)
]

In [ ]:
high_sales_low_profit.sort_values(
    "Total_Sales",
    ascending=False
)

In [82]:
conn=mysql.connector.connect(
    host="localhost",
    user='root',
    password='root123',
    database='ecommerce_analysis'
)
cursor=conn.cursor()
engine=create_engine(
    "mysql+mysqlconnector://root:root123@localhost/ecommerce_analysis"
)
print("Connected Successfully")

Connected Successfully

In [79]:
df.to_sql(
    name='data_clean',
    con=engine,
    if_exists='replace',
    index=False
)
print("Load successfully")

Load successfully